// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.project.service2;

public final class Service2OuterClass {
  private Service2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface tariffsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tariffsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tariffsRequest.Country country = 1;</code>
     */
    int getCountryValue();
    /**
     * <code>.tariffsRequest.Country country = 1;</code>
     */
    ds.project.service2.Service2OuterClass.tariffsRequest.Country getCountry();

    /**
     * <code>.tariffsRequest.Service service = 2;</code>
     */
    int getServiceValue();
    /**
     * <code>.tariffsRequest.Service service = 2;</code>
     */
    ds.project.service2.Service2OuterClass.tariffsRequest.Service getService();
  }
  /**
   * Protobuf type {@code tariffsRequest}
   */
  public  static final class tariffsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tariffsRequest)
      tariffsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use tariffsRequest.newBuilder() to construct.
    private tariffsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private tariffsRequest() {
      country_ = 0;
      service_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private tariffsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              country_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              service_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service2.Service2OuterClass.internal_static_tariffsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service2.Service2OuterClass.internal_static_tariffsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service2.Service2OuterClass.tariffsRequest.class, ds.project.service2.Service2OuterClass.tariffsRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code tariffsRequest.Country}
     */
    public enum Country
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Ireland = 0;</code>
       */
      Ireland(0),
      /**
       * <code>Germany = 1;</code>
       */
      Germany(1),
      /**
       * <code>France = 2;</code>
       */
      France(2),
      /**
       * <code>Switzerland = 3;</code>
       */
      Switzerland(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Ireland = 0;</code>
       */
      public static final int Ireland_VALUE = 0;
      /**
       * <code>Germany = 1;</code>
       */
      public static final int Germany_VALUE = 1;
      /**
       * <code>France = 2;</code>
       */
      public static final int France_VALUE = 2;
      /**
       * <code>Switzerland = 3;</code>
       */
      public static final int Switzerland_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Country valueOf(int value) {
        return forNumber(value);
      }

      public static Country forNumber(int value) {
        switch (value) {
          case 0: return Ireland;
          case 1: return Germany;
          case 2: return France;
          case 3: return Switzerland;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Country>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Country> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Country>() {
              public Country findValueByNumber(int number) {
                return Country.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ds.project.service2.Service2OuterClass.tariffsRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Country[] VALUES = values();

      public static Country valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Country(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tariffsRequest.Country)
    }

    /**
     * Protobuf enum {@code tariffsRequest.Service}
     */
    public enum Service
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Gas = 0;</code>
       */
      Gas(0),
      /**
       * <code>Electricity = 1;</code>
       */
      Electricity(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Gas = 0;</code>
       */
      public static final int Gas_VALUE = 0;
      /**
       * <code>Electricity = 1;</code>
       */
      public static final int Electricity_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Service valueOf(int value) {
        return forNumber(value);
      }

      public static Service forNumber(int value) {
        switch (value) {
          case 0: return Gas;
          case 1: return Electricity;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Service>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Service> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Service>() {
              public Service findValueByNumber(int number) {
                return Service.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ds.project.service2.Service2OuterClass.tariffsRequest.getDescriptor().getEnumTypes().get(1);
      }

      private static final Service[] VALUES = values();

      public static Service valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Service(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tariffsRequest.Service)
    }

    public static final int COUNTRY_FIELD_NUMBER = 1;
    private int country_;
    /**
     * <code>.tariffsRequest.Country country = 1;</code>
     */
    public int getCountryValue() {
      return country_;
    }
    /**
     * <code>.tariffsRequest.Country country = 1;</code>
     */
    public ds.project.service2.Service2OuterClass.tariffsRequest.Country getCountry() {
      @SuppressWarnings("deprecation")
      ds.project.service2.Service2OuterClass.tariffsRequest.Country result = ds.project.service2.Service2OuterClass.tariffsRequest.Country.valueOf(country_);
      return result == null ? ds.project.service2.Service2OuterClass.tariffsRequest.Country.UNRECOGNIZED : result;
    }

    public static final int SERVICE_FIELD_NUMBER = 2;
    private int service_;
    /**
     * <code>.tariffsRequest.Service service = 2;</code>
     */
    public int getServiceValue() {
      return service_;
    }
    /**
     * <code>.tariffsRequest.Service service = 2;</code>
     */
    public ds.project.service2.Service2OuterClass.tariffsRequest.Service getService() {
      @SuppressWarnings("deprecation")
      ds.project.service2.Service2OuterClass.tariffsRequest.Service result = ds.project.service2.Service2OuterClass.tariffsRequest.Service.valueOf(service_);
      return result == null ? ds.project.service2.Service2OuterClass.tariffsRequest.Service.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (country_ != ds.project.service2.Service2OuterClass.tariffsRequest.Country.Ireland.getNumber()) {
        output.writeEnum(1, country_);
      }
      if (service_ != ds.project.service2.Service2OuterClass.tariffsRequest.Service.Gas.getNumber()) {
        output.writeEnum(2, service_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (country_ != ds.project.service2.Service2OuterClass.tariffsRequest.Country.Ireland.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, country_);
      }
      if (service_ != ds.project.service2.Service2OuterClass.tariffsRequest.Service.Gas.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, service_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service2.Service2OuterClass.tariffsRequest)) {
        return super.equals(obj);
      }
      ds.project.service2.Service2OuterClass.tariffsRequest other = (ds.project.service2.Service2OuterClass.tariffsRequest) obj;

      boolean result = true;
      result = result && country_ == other.country_;
      result = result && service_ == other.service_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + country_;
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + service_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.tariffsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service2.Service2OuterClass.tariffsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tariffsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tariffsRequest)
        ds.project.service2.Service2OuterClass.tariffsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service2.Service2OuterClass.internal_static_tariffsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service2.Service2OuterClass.internal_static_tariffsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service2.Service2OuterClass.tariffsRequest.class, ds.project.service2.Service2OuterClass.tariffsRequest.Builder.class);
      }

      // Construct using ds.project.service2.Service2OuterClass.tariffsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        country_ = 0;

        service_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service2.Service2OuterClass.internal_static_tariffsRequest_descriptor;
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.tariffsRequest getDefaultInstanceForType() {
        return ds.project.service2.Service2OuterClass.tariffsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.tariffsRequest build() {
        ds.project.service2.Service2OuterClass.tariffsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.tariffsRequest buildPartial() {
        ds.project.service2.Service2OuterClass.tariffsRequest result = new ds.project.service2.Service2OuterClass.tariffsRequest(this);
        result.country_ = country_;
        result.service_ = service_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service2.Service2OuterClass.tariffsRequest) {
          return mergeFrom((ds.project.service2.Service2OuterClass.tariffsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service2.Service2OuterClass.tariffsRequest other) {
        if (other == ds.project.service2.Service2OuterClass.tariffsRequest.getDefaultInstance()) return this;
        if (other.country_ != 0) {
          setCountryValue(other.getCountryValue());
        }
        if (other.service_ != 0) {
          setServiceValue(other.getServiceValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service2.Service2OuterClass.tariffsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service2.Service2OuterClass.tariffsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int country_ = 0;
      /**
       * <code>.tariffsRequest.Country country = 1;</code>
       */
      public int getCountryValue() {
        return country_;
      }
      /**
       * <code>.tariffsRequest.Country country = 1;</code>
       */
      public Builder setCountryValue(int value) {
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tariffsRequest.Country country = 1;</code>
       */
      public ds.project.service2.Service2OuterClass.tariffsRequest.Country getCountry() {
        @SuppressWarnings("deprecation")
        ds.project.service2.Service2OuterClass.tariffsRequest.Country result = ds.project.service2.Service2OuterClass.tariffsRequest.Country.valueOf(country_);
        return result == null ? ds.project.service2.Service2OuterClass.tariffsRequest.Country.UNRECOGNIZED : result;
      }
      /**
       * <code>.tariffsRequest.Country country = 1;</code>
       */
      public Builder setCountry(ds.project.service2.Service2OuterClass.tariffsRequest.Country value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        country_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tariffsRequest.Country country = 1;</code>
       */
      public Builder clearCountry() {
        
        country_ = 0;
        onChanged();
        return this;
      }

      private int service_ = 0;
      /**
       * <code>.tariffsRequest.Service service = 2;</code>
       */
      public int getServiceValue() {
        return service_;
      }
      /**
       * <code>.tariffsRequest.Service service = 2;</code>
       */
      public Builder setServiceValue(int value) {
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tariffsRequest.Service service = 2;</code>
       */
      public ds.project.service2.Service2OuterClass.tariffsRequest.Service getService() {
        @SuppressWarnings("deprecation")
        ds.project.service2.Service2OuterClass.tariffsRequest.Service result = ds.project.service2.Service2OuterClass.tariffsRequest.Service.valueOf(service_);
        return result == null ? ds.project.service2.Service2OuterClass.tariffsRequest.Service.UNRECOGNIZED : result;
      }
      /**
       * <code>.tariffsRequest.Service service = 2;</code>
       */
      public Builder setService(ds.project.service2.Service2OuterClass.tariffsRequest.Service value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        service_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tariffsRequest.Service service = 2;</code>
       */
      public Builder clearService() {
        
        service_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tariffsRequest)
    }

    // @@protoc_insertion_point(class_scope:tariffsRequest)
    private static final ds.project.service2.Service2OuterClass.tariffsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service2.Service2OuterClass.tariffsRequest();
    }

    public static ds.project.service2.Service2OuterClass.tariffsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<tariffsRequest>
        PARSER = new com.google.protobuf.AbstractParser<tariffsRequest>() {
      @java.lang.Override
      public tariffsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new tariffsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<tariffsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<tariffsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service2.Service2OuterClass.tariffsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TariffsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tariffs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tariffs = 1;</code>
     */
    java.lang.String getTariffs();
    /**
     * <code>string tariffs = 1;</code>
     */
    com.google.protobuf.ByteString
        getTariffsBytes();
  }
  /**
   * Protobuf type {@code Tariffs}
   */
  public  static final class Tariffs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tariffs)
      TariffsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tariffs.newBuilder() to construct.
    private Tariffs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tariffs() {
      tariffs_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tariffs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tariffs_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service2.Service2OuterClass.internal_static_Tariffs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service2.Service2OuterClass.internal_static_Tariffs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service2.Service2OuterClass.Tariffs.class, ds.project.service2.Service2OuterClass.Tariffs.Builder.class);
    }

    public static final int TARIFFS_FIELD_NUMBER = 1;
    private volatile java.lang.Object tariffs_;
    /**
     * <code>string tariffs = 1;</code>
     */
    public java.lang.String getTariffs() {
      java.lang.Object ref = tariffs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tariffs_ = s;
        return s;
      }
    }
    /**
     * <code>string tariffs = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTariffsBytes() {
      java.lang.Object ref = tariffs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tariffs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTariffsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tariffs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTariffsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tariffs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service2.Service2OuterClass.Tariffs)) {
        return super.equals(obj);
      }
      ds.project.service2.Service2OuterClass.Tariffs other = (ds.project.service2.Service2OuterClass.Tariffs) obj;

      boolean result = true;
      result = result && getTariffs()
          .equals(other.getTariffs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARIFFS_FIELD_NUMBER;
      hash = (53 * hash) + getTariffs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service2.Service2OuterClass.Tariffs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service2.Service2OuterClass.Tariffs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tariffs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tariffs)
        ds.project.service2.Service2OuterClass.TariffsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service2.Service2OuterClass.internal_static_Tariffs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service2.Service2OuterClass.internal_static_Tariffs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service2.Service2OuterClass.Tariffs.class, ds.project.service2.Service2OuterClass.Tariffs.Builder.class);
      }

      // Construct using ds.project.service2.Service2OuterClass.Tariffs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tariffs_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service2.Service2OuterClass.internal_static_Tariffs_descriptor;
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.Tariffs getDefaultInstanceForType() {
        return ds.project.service2.Service2OuterClass.Tariffs.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.Tariffs build() {
        ds.project.service2.Service2OuterClass.Tariffs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service2.Service2OuterClass.Tariffs buildPartial() {
        ds.project.service2.Service2OuterClass.Tariffs result = new ds.project.service2.Service2OuterClass.Tariffs(this);
        result.tariffs_ = tariffs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service2.Service2OuterClass.Tariffs) {
          return mergeFrom((ds.project.service2.Service2OuterClass.Tariffs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service2.Service2OuterClass.Tariffs other) {
        if (other == ds.project.service2.Service2OuterClass.Tariffs.getDefaultInstance()) return this;
        if (!other.getTariffs().isEmpty()) {
          tariffs_ = other.tariffs_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service2.Service2OuterClass.Tariffs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service2.Service2OuterClass.Tariffs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tariffs_ = "";
      /**
       * <code>string tariffs = 1;</code>
       */
      public java.lang.String getTariffs() {
        java.lang.Object ref = tariffs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tariffs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tariffs = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTariffsBytes() {
        java.lang.Object ref = tariffs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tariffs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tariffs = 1;</code>
       */
      public Builder setTariffs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tariffs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tariffs = 1;</code>
       */
      public Builder clearTariffs() {
        
        tariffs_ = getDefaultInstance().getTariffs();
        onChanged();
        return this;
      }
      /**
       * <code>string tariffs = 1;</code>
       */
      public Builder setTariffsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tariffs_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tariffs)
    }

    // @@protoc_insertion_point(class_scope:Tariffs)
    private static final ds.project.service2.Service2OuterClass.Tariffs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service2.Service2OuterClass.Tariffs();
    }

    public static ds.project.service2.Service2OuterClass.Tariffs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tariffs>
        PARSER = new com.google.protobuf.AbstractParser<Tariffs>() {
      @java.lang.Override
      public Tariffs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tariffs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tariffs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tariffs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service2.Service2OuterClass.Tariffs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tariffsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tariffsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tariffs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tariffs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\"\313\001\n\016tariffsRequest\022(\n\007c" +
      "ountry\030\001 \001(\0162\027.tariffsRequest.Country\022(\n" +
      "\007service\030\002 \001(\0162\027.tariffsRequest.Service\"" +
      "@\n\007Country\022\013\n\007Ireland\020\000\022\013\n\007Germany\020\001\022\n\n\006" +
      "France\020\002\022\017\n\013Switzerland\020\003\"#\n\007Service\022\007\n\003" +
      "Gas\020\000\022\017\n\013Electricity\020\001\"\032\n\007Tariffs\022\017\n\007tar" +
      "iffs\030\001 \001(\t25\n\010Service2\022)\n\ngetTariffs\022\017.t" +
      "ariffsRequest\032\010.Tariffs0\001B\025\n\023ds.project." +
      "service2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tariffsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tariffsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tariffsRequest_descriptor,
        new java.lang.String[] { "Country", "Service", });
    internal_static_Tariffs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Tariffs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tariffs_descriptor,
        new java.lang.String[] { "Tariffs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
