// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.project.service3;

public final class Service3OuterClass {
  private Service3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface scheduleRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scheduleRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string startDate = 1;</code>
     */
    java.lang.String getStartDate();
    /**
     * <code>string startDate = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartDateBytes();

    /**
     * <code>string endDate = 2;</code>
     */
    java.lang.String getEndDate();
    /**
     * <code>string endDate = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndDateBytes();
  }
  /**
   * Protobuf type {@code scheduleRequest}
   */
  public  static final class scheduleRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:scheduleRequest)
      scheduleRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use scheduleRequest.newBuilder() to construct.
    private scheduleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private scheduleRequest() {
      startDate_ = "";
      endDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private scheduleRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              startDate_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              endDate_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service3.Service3OuterClass.internal_static_scheduleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service3.Service3OuterClass.internal_static_scheduleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service3.Service3OuterClass.scheduleRequest.class, ds.project.service3.Service3OuterClass.scheduleRequest.Builder.class);
    }

    public static final int STARTDATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object startDate_;
    /**
     * <code>string startDate = 1;</code>
     */
    public java.lang.String getStartDate() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startDate_ = s;
        return s;
      }
    }
    /**
     * <code>string startDate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDDATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object endDate_;
    /**
     * <code>string endDate = 2;</code>
     */
    public java.lang.String getEndDate() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endDate_ = s;
        return s;
      }
    }
    /**
     * <code>string endDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndDateBytes() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStartDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, startDate_);
      }
      if (!getEndDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, endDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStartDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, startDate_);
      }
      if (!getEndDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, endDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service3.Service3OuterClass.scheduleRequest)) {
        return super.equals(obj);
      }
      ds.project.service3.Service3OuterClass.scheduleRequest other = (ds.project.service3.Service3OuterClass.scheduleRequest) obj;

      boolean result = true;
      result = result && getStartDate()
          .equals(other.getStartDate());
      result = result && getEndDate()
          .equals(other.getEndDate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.scheduleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service3.Service3OuterClass.scheduleRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scheduleRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scheduleRequest)
        ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service3.Service3OuterClass.internal_static_scheduleRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service3.Service3OuterClass.internal_static_scheduleRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service3.Service3OuterClass.scheduleRequest.class, ds.project.service3.Service3OuterClass.scheduleRequest.Builder.class);
      }

      // Construct using ds.project.service3.Service3OuterClass.scheduleRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startDate_ = "";

        endDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service3.Service3OuterClass.internal_static_scheduleRequest_descriptor;
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.scheduleRequest getDefaultInstanceForType() {
        return ds.project.service3.Service3OuterClass.scheduleRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.scheduleRequest build() {
        ds.project.service3.Service3OuterClass.scheduleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.scheduleRequest buildPartial() {
        ds.project.service3.Service3OuterClass.scheduleRequest result = new ds.project.service3.Service3OuterClass.scheduleRequest(this);
        result.startDate_ = startDate_;
        result.endDate_ = endDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service3.Service3OuterClass.scheduleRequest) {
          return mergeFrom((ds.project.service3.Service3OuterClass.scheduleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service3.Service3OuterClass.scheduleRequest other) {
        if (other == ds.project.service3.Service3OuterClass.scheduleRequest.getDefaultInstance()) return this;
        if (!other.getStartDate().isEmpty()) {
          startDate_ = other.startDate_;
          onChanged();
        }
        if (!other.getEndDate().isEmpty()) {
          endDate_ = other.endDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service3.Service3OuterClass.scheduleRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service3.Service3OuterClass.scheduleRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object startDate_ = "";
      /**
       * <code>string startDate = 1;</code>
       */
      public java.lang.String getStartDate() {
        java.lang.Object ref = startDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string startDate = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartDateBytes() {
        java.lang.Object ref = startDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startDate = 1;</code>
       */
      public Builder setStartDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string startDate = 1;</code>
       */
      public Builder clearStartDate() {
        
        startDate_ = getDefaultInstance().getStartDate();
        onChanged();
        return this;
      }
      /**
       * <code>string startDate = 1;</code>
       */
      public Builder setStartDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endDate_ = "";
      /**
       * <code>string endDate = 2;</code>
       */
      public java.lang.String getEndDate() {
        java.lang.Object ref = endDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endDate = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndDateBytes() {
        java.lang.Object ref = endDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endDate = 2;</code>
       */
      public Builder setEndDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endDate = 2;</code>
       */
      public Builder clearEndDate() {
        
        endDate_ = getDefaultInstance().getEndDate();
        onChanged();
        return this;
      }
      /**
       * <code>string endDate = 2;</code>
       */
      public Builder setEndDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:scheduleRequest)
    }

    // @@protoc_insertion_point(class_scope:scheduleRequest)
    private static final ds.project.service3.Service3OuterClass.scheduleRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service3.Service3OuterClass.scheduleRequest();
    }

    public static ds.project.service3.Service3OuterClass.scheduleRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<scheduleRequest>
        PARSER = new com.google.protobuf.AbstractParser<scheduleRequest>() {
      @java.lang.Override
      public scheduleRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new scheduleRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<scheduleRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<scheduleRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service3.Service3OuterClass.scheduleRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScheduleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Schedule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest> 
        getUpdatedScheduleRequestList();
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    ds.project.service3.Service3OuterClass.scheduleRequest getUpdatedScheduleRequest(int index);
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    int getUpdatedScheduleRequestCount();
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    java.util.List<? extends ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder> 
        getUpdatedScheduleRequestOrBuilderList();
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder getUpdatedScheduleRequestOrBuilder(
        int index);

    /**
     * <code>string error = 2;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code Schedule}
   */
  public  static final class Schedule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Schedule)
      ScheduleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Schedule.newBuilder() to construct.
    private Schedule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Schedule() {
      updatedScheduleRequest_ = java.util.Collections.emptyList();
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Schedule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                updatedScheduleRequest_ = new java.util.ArrayList<ds.project.service3.Service3OuterClass.scheduleRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              updatedScheduleRequest_.add(
                  input.readMessage(ds.project.service3.Service3OuterClass.scheduleRequest.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          updatedScheduleRequest_ = java.util.Collections.unmodifiableList(updatedScheduleRequest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service3.Service3OuterClass.internal_static_Schedule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service3.Service3OuterClass.internal_static_Schedule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service3.Service3OuterClass.Schedule.class, ds.project.service3.Service3OuterClass.Schedule.Builder.class);
    }

    private int bitField0_;
    public static final int UPDATEDSCHEDULEREQUEST_FIELD_NUMBER = 1;
    private java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest> updatedScheduleRequest_;
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    public java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest> getUpdatedScheduleRequestList() {
      return updatedScheduleRequest_;
    }
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    public java.util.List<? extends ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder> 
        getUpdatedScheduleRequestOrBuilderList() {
      return updatedScheduleRequest_;
    }
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    public int getUpdatedScheduleRequestCount() {
      return updatedScheduleRequest_.size();
    }
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    public ds.project.service3.Service3OuterClass.scheduleRequest getUpdatedScheduleRequest(int index) {
      return updatedScheduleRequest_.get(index);
    }
    /**
     * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
     */
    public ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder getUpdatedScheduleRequestOrBuilder(
        int index) {
      return updatedScheduleRequest_.get(index);
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 2;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < updatedScheduleRequest_.size(); i++) {
        output.writeMessage(1, updatedScheduleRequest_.get(i));
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < updatedScheduleRequest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updatedScheduleRequest_.get(i));
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service3.Service3OuterClass.Schedule)) {
        return super.equals(obj);
      }
      ds.project.service3.Service3OuterClass.Schedule other = (ds.project.service3.Service3OuterClass.Schedule) obj;

      boolean result = true;
      result = result && getUpdatedScheduleRequestList()
          .equals(other.getUpdatedScheduleRequestList());
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUpdatedScheduleRequestCount() > 0) {
        hash = (37 * hash) + UPDATEDSCHEDULEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedScheduleRequestList().hashCode();
      }
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service3.Service3OuterClass.Schedule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service3.Service3OuterClass.Schedule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Schedule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Schedule)
        ds.project.service3.Service3OuterClass.ScheduleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service3.Service3OuterClass.internal_static_Schedule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service3.Service3OuterClass.internal_static_Schedule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service3.Service3OuterClass.Schedule.class, ds.project.service3.Service3OuterClass.Schedule.Builder.class);
      }

      // Construct using ds.project.service3.Service3OuterClass.Schedule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUpdatedScheduleRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (updatedScheduleRequestBuilder_ == null) {
          updatedScheduleRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updatedScheduleRequestBuilder_.clear();
        }
        error_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service3.Service3OuterClass.internal_static_Schedule_descriptor;
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.Schedule getDefaultInstanceForType() {
        return ds.project.service3.Service3OuterClass.Schedule.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.Schedule build() {
        ds.project.service3.Service3OuterClass.Schedule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service3.Service3OuterClass.Schedule buildPartial() {
        ds.project.service3.Service3OuterClass.Schedule result = new ds.project.service3.Service3OuterClass.Schedule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (updatedScheduleRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updatedScheduleRequest_ = java.util.Collections.unmodifiableList(updatedScheduleRequest_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updatedScheduleRequest_ = updatedScheduleRequest_;
        } else {
          result.updatedScheduleRequest_ = updatedScheduleRequestBuilder_.build();
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service3.Service3OuterClass.Schedule) {
          return mergeFrom((ds.project.service3.Service3OuterClass.Schedule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service3.Service3OuterClass.Schedule other) {
        if (other == ds.project.service3.Service3OuterClass.Schedule.getDefaultInstance()) return this;
        if (updatedScheduleRequestBuilder_ == null) {
          if (!other.updatedScheduleRequest_.isEmpty()) {
            if (updatedScheduleRequest_.isEmpty()) {
              updatedScheduleRequest_ = other.updatedScheduleRequest_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdatedScheduleRequestIsMutable();
              updatedScheduleRequest_.addAll(other.updatedScheduleRequest_);
            }
            onChanged();
          }
        } else {
          if (!other.updatedScheduleRequest_.isEmpty()) {
            if (updatedScheduleRequestBuilder_.isEmpty()) {
              updatedScheduleRequestBuilder_.dispose();
              updatedScheduleRequestBuilder_ = null;
              updatedScheduleRequest_ = other.updatedScheduleRequest_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updatedScheduleRequestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUpdatedScheduleRequestFieldBuilder() : null;
            } else {
              updatedScheduleRequestBuilder_.addAllMessages(other.updatedScheduleRequest_);
            }
          }
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service3.Service3OuterClass.Schedule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service3.Service3OuterClass.Schedule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest> updatedScheduleRequest_ =
        java.util.Collections.emptyList();
      private void ensureUpdatedScheduleRequestIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updatedScheduleRequest_ = new java.util.ArrayList<ds.project.service3.Service3OuterClass.scheduleRequest>(updatedScheduleRequest_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ds.project.service3.Service3OuterClass.scheduleRequest, ds.project.service3.Service3OuterClass.scheduleRequest.Builder, ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder> updatedScheduleRequestBuilder_;

      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest> getUpdatedScheduleRequestList() {
        if (updatedScheduleRequestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updatedScheduleRequest_);
        } else {
          return updatedScheduleRequestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public int getUpdatedScheduleRequestCount() {
        if (updatedScheduleRequestBuilder_ == null) {
          return updatedScheduleRequest_.size();
        } else {
          return updatedScheduleRequestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public ds.project.service3.Service3OuterClass.scheduleRequest getUpdatedScheduleRequest(int index) {
        if (updatedScheduleRequestBuilder_ == null) {
          return updatedScheduleRequest_.get(index);
        } else {
          return updatedScheduleRequestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder setUpdatedScheduleRequest(
          int index, ds.project.service3.Service3OuterClass.scheduleRequest value) {
        if (updatedScheduleRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.set(index, value);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder setUpdatedScheduleRequest(
          int index, ds.project.service3.Service3OuterClass.scheduleRequest.Builder builderForValue) {
        if (updatedScheduleRequestBuilder_ == null) {
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.set(index, builderForValue.build());
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder addUpdatedScheduleRequest(ds.project.service3.Service3OuterClass.scheduleRequest value) {
        if (updatedScheduleRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.add(value);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder addUpdatedScheduleRequest(
          int index, ds.project.service3.Service3OuterClass.scheduleRequest value) {
        if (updatedScheduleRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.add(index, value);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder addUpdatedScheduleRequest(
          ds.project.service3.Service3OuterClass.scheduleRequest.Builder builderForValue) {
        if (updatedScheduleRequestBuilder_ == null) {
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.add(builderForValue.build());
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder addUpdatedScheduleRequest(
          int index, ds.project.service3.Service3OuterClass.scheduleRequest.Builder builderForValue) {
        if (updatedScheduleRequestBuilder_ == null) {
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.add(index, builderForValue.build());
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder addAllUpdatedScheduleRequest(
          java.lang.Iterable<? extends ds.project.service3.Service3OuterClass.scheduleRequest> values) {
        if (updatedScheduleRequestBuilder_ == null) {
          ensureUpdatedScheduleRequestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, updatedScheduleRequest_);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder clearUpdatedScheduleRequest() {
        if (updatedScheduleRequestBuilder_ == null) {
          updatedScheduleRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public Builder removeUpdatedScheduleRequest(int index) {
        if (updatedScheduleRequestBuilder_ == null) {
          ensureUpdatedScheduleRequestIsMutable();
          updatedScheduleRequest_.remove(index);
          onChanged();
        } else {
          updatedScheduleRequestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public ds.project.service3.Service3OuterClass.scheduleRequest.Builder getUpdatedScheduleRequestBuilder(
          int index) {
        return getUpdatedScheduleRequestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder getUpdatedScheduleRequestOrBuilder(
          int index) {
        if (updatedScheduleRequestBuilder_ == null) {
          return updatedScheduleRequest_.get(index);  } else {
          return updatedScheduleRequestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public java.util.List<? extends ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder> 
           getUpdatedScheduleRequestOrBuilderList() {
        if (updatedScheduleRequestBuilder_ != null) {
          return updatedScheduleRequestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updatedScheduleRequest_);
        }
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public ds.project.service3.Service3OuterClass.scheduleRequest.Builder addUpdatedScheduleRequestBuilder() {
        return getUpdatedScheduleRequestFieldBuilder().addBuilder(
            ds.project.service3.Service3OuterClass.scheduleRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public ds.project.service3.Service3OuterClass.scheduleRequest.Builder addUpdatedScheduleRequestBuilder(
          int index) {
        return getUpdatedScheduleRequestFieldBuilder().addBuilder(
            index, ds.project.service3.Service3OuterClass.scheduleRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .scheduleRequest updatedScheduleRequest = 1;</code>
       */
      public java.util.List<ds.project.service3.Service3OuterClass.scheduleRequest.Builder> 
           getUpdatedScheduleRequestBuilderList() {
        return getUpdatedScheduleRequestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ds.project.service3.Service3OuterClass.scheduleRequest, ds.project.service3.Service3OuterClass.scheduleRequest.Builder, ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder> 
          getUpdatedScheduleRequestFieldBuilder() {
        if (updatedScheduleRequestBuilder_ == null) {
          updatedScheduleRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ds.project.service3.Service3OuterClass.scheduleRequest, ds.project.service3.Service3OuterClass.scheduleRequest.Builder, ds.project.service3.Service3OuterClass.scheduleRequestOrBuilder>(
                  updatedScheduleRequest_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updatedScheduleRequest_ = null;
        }
        return updatedScheduleRequestBuilder_;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 2;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Schedule)
    }

    // @@protoc_insertion_point(class_scope:Schedule)
    private static final ds.project.service3.Service3OuterClass.Schedule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service3.Service3OuterClass.Schedule();
    }

    public static ds.project.service3.Service3OuterClass.Schedule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Schedule>
        PARSER = new com.google.protobuf.AbstractParser<Schedule>() {
      @java.lang.Override
      public Schedule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Schedule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Schedule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Schedule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service3.Service3OuterClass.Schedule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduleRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scheduleRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Schedule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Schedule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\"5\n\017scheduleRequest\022\021\n\ts" +
      "tartDate\030\001 \001(\t\022\017\n\007endDate\030\002 \001(\t\"K\n\010Sched" +
      "ule\0220\n\026updatedScheduleRequest\030\001 \003(\0132\020.sc" +
      "heduleRequest\022\r\n\005error\030\002 \001(\t28\n\010Service3" +
      "\022,\n\013getSchedule\022\020.scheduleRequest\032\t.Sche" +
      "dule(\001B\025\n\023ds.project.service3b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_scheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scheduleRequest_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
    internal_static_Schedule_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Schedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Schedule_descriptor,
        new java.lang.String[] { "UpdatedScheduleRequest", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
