// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.project.service1;

public final class Service1OuterClass {
  private Service1OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeatOutputRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeatOutputRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double width_room = 1;</code>
     */
    double getWidthRoom();

    /**
     * <code>double length_room = 2;</code>
     */
    double getLengthRoom();

    /**
     * <code>double height_room = 3;</code>
     */
    double getHeightRoom();
  }
  /**
   * Protobuf type {@code HeatOutputRequest}
   */
  public  static final class HeatOutputRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeatOutputRequest)
      HeatOutputRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeatOutputRequest.newBuilder() to construct.
    private HeatOutputRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeatOutputRequest() {
      widthRoom_ = 0D;
      lengthRoom_ = 0D;
      heightRoom_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeatOutputRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              widthRoom_ = input.readDouble();
              break;
            }
            case 17: {

              lengthRoom_ = input.readDouble();
              break;
            }
            case 25: {

              heightRoom_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service1.Service1OuterClass.internal_static_HeatOutputRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service1.Service1OuterClass.internal_static_HeatOutputRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service1.Service1OuterClass.HeatOutputRequest.class, ds.project.service1.Service1OuterClass.HeatOutputRequest.Builder.class);
    }

    public static final int WIDTH_ROOM_FIELD_NUMBER = 1;
    private double widthRoom_;
    /**
     * <code>double width_room = 1;</code>
     */
    public double getWidthRoom() {
      return widthRoom_;
    }

    public static final int LENGTH_ROOM_FIELD_NUMBER = 2;
    private double lengthRoom_;
    /**
     * <code>double length_room = 2;</code>
     */
    public double getLengthRoom() {
      return lengthRoom_;
    }

    public static final int HEIGHT_ROOM_FIELD_NUMBER = 3;
    private double heightRoom_;
    /**
     * <code>double height_room = 3;</code>
     */
    public double getHeightRoom() {
      return heightRoom_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (widthRoom_ != 0D) {
        output.writeDouble(1, widthRoom_);
      }
      if (lengthRoom_ != 0D) {
        output.writeDouble(2, lengthRoom_);
      }
      if (heightRoom_ != 0D) {
        output.writeDouble(3, heightRoom_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (widthRoom_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, widthRoom_);
      }
      if (lengthRoom_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lengthRoom_);
      }
      if (heightRoom_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, heightRoom_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service1.Service1OuterClass.HeatOutputRequest)) {
        return super.equals(obj);
      }
      ds.project.service1.Service1OuterClass.HeatOutputRequest other = (ds.project.service1.Service1OuterClass.HeatOutputRequest) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getWidthRoom())
          == java.lang.Double.doubleToLongBits(
              other.getWidthRoom()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLengthRoom())
          == java.lang.Double.doubleToLongBits(
              other.getLengthRoom()));
      result = result && (
          java.lang.Double.doubleToLongBits(getHeightRoom())
          == java.lang.Double.doubleToLongBits(
              other.getHeightRoom()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_ROOM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWidthRoom()));
      hash = (37 * hash) + LENGTH_ROOM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLengthRoom()));
      hash = (37 * hash) + HEIGHT_ROOM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeightRoom()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutputRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service1.Service1OuterClass.HeatOutputRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeatOutputRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeatOutputRequest)
        ds.project.service1.Service1OuterClass.HeatOutputRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutputRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutputRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service1.Service1OuterClass.HeatOutputRequest.class, ds.project.service1.Service1OuterClass.HeatOutputRequest.Builder.class);
      }

      // Construct using ds.project.service1.Service1OuterClass.HeatOutputRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        widthRoom_ = 0D;

        lengthRoom_ = 0D;

        heightRoom_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutputRequest_descriptor;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutputRequest getDefaultInstanceForType() {
        return ds.project.service1.Service1OuterClass.HeatOutputRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutputRequest build() {
        ds.project.service1.Service1OuterClass.HeatOutputRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutputRequest buildPartial() {
        ds.project.service1.Service1OuterClass.HeatOutputRequest result = new ds.project.service1.Service1OuterClass.HeatOutputRequest(this);
        result.widthRoom_ = widthRoom_;
        result.lengthRoom_ = lengthRoom_;
        result.heightRoom_ = heightRoom_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service1.Service1OuterClass.HeatOutputRequest) {
          return mergeFrom((ds.project.service1.Service1OuterClass.HeatOutputRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service1.Service1OuterClass.HeatOutputRequest other) {
        if (other == ds.project.service1.Service1OuterClass.HeatOutputRequest.getDefaultInstance()) return this;
        if (other.getWidthRoom() != 0D) {
          setWidthRoom(other.getWidthRoom());
        }
        if (other.getLengthRoom() != 0D) {
          setLengthRoom(other.getLengthRoom());
        }
        if (other.getHeightRoom() != 0D) {
          setHeightRoom(other.getHeightRoom());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service1.Service1OuterClass.HeatOutputRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service1.Service1OuterClass.HeatOutputRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double widthRoom_ ;
      /**
       * <code>double width_room = 1;</code>
       */
      public double getWidthRoom() {
        return widthRoom_;
      }
      /**
       * <code>double width_room = 1;</code>
       */
      public Builder setWidthRoom(double value) {
        
        widthRoom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double width_room = 1;</code>
       */
      public Builder clearWidthRoom() {
        
        widthRoom_ = 0D;
        onChanged();
        return this;
      }

      private double lengthRoom_ ;
      /**
       * <code>double length_room = 2;</code>
       */
      public double getLengthRoom() {
        return lengthRoom_;
      }
      /**
       * <code>double length_room = 2;</code>
       */
      public Builder setLengthRoom(double value) {
        
        lengthRoom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double length_room = 2;</code>
       */
      public Builder clearLengthRoom() {
        
        lengthRoom_ = 0D;
        onChanged();
        return this;
      }

      private double heightRoom_ ;
      /**
       * <code>double height_room = 3;</code>
       */
      public double getHeightRoom() {
        return heightRoom_;
      }
      /**
       * <code>double height_room = 3;</code>
       */
      public Builder setHeightRoom(double value) {
        
        heightRoom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double height_room = 3;</code>
       */
      public Builder clearHeightRoom() {
        
        heightRoom_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeatOutputRequest)
    }

    // @@protoc_insertion_point(class_scope:HeatOutputRequest)
    private static final ds.project.service1.Service1OuterClass.HeatOutputRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service1.Service1OuterClass.HeatOutputRequest();
    }

    public static ds.project.service1.Service1OuterClass.HeatOutputRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeatOutputRequest>
        PARSER = new com.google.protobuf.AbstractParser<HeatOutputRequest>() {
      @java.lang.Override
      public HeatOutputRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeatOutputRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeatOutputRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeatOutputRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service1.Service1OuterClass.HeatOutputRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeatOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeatOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double kW = 1;</code>
     */
    double getKW();

    /**
     * <code>double BTU = 2;</code>
     */
    double getBTU();

    /**
     * <code>string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code HeatOutput}
   */
  public  static final class HeatOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeatOutput)
      HeatOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeatOutput.newBuilder() to construct.
    private HeatOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeatOutput() {
      kW_ = 0D;
      bTU_ = 0D;
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeatOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              kW_ = input.readDouble();
              break;
            }
            case 17: {

              bTU_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service1.Service1OuterClass.internal_static_HeatOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service1.Service1OuterClass.internal_static_HeatOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service1.Service1OuterClass.HeatOutput.class, ds.project.service1.Service1OuterClass.HeatOutput.Builder.class);
    }

    public static final int KW_FIELD_NUMBER = 1;
    private double kW_;
    /**
     * <code>double kW = 1;</code>
     */
    public double getKW() {
      return kW_;
    }

    public static final int BTU_FIELD_NUMBER = 2;
    private double bTU_;
    /**
     * <code>double BTU = 2;</code>
     */
    public double getBTU() {
      return bTU_;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (kW_ != 0D) {
        output.writeDouble(1, kW_);
      }
      if (bTU_ != 0D) {
        output.writeDouble(2, bTU_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, error_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (kW_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, kW_);
      }
      if (bTU_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, bTU_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service1.Service1OuterClass.HeatOutput)) {
        return super.equals(obj);
      }
      ds.project.service1.Service1OuterClass.HeatOutput other = (ds.project.service1.Service1OuterClass.HeatOutput) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getKW())
          == java.lang.Double.doubleToLongBits(
              other.getKW()));
      result = result && (
          java.lang.Double.doubleToLongBits(getBTU())
          == java.lang.Double.doubleToLongBits(
              other.getBTU()));
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKW()));
      hash = (37 * hash) + BTU_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBTU()));
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.HeatOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service1.Service1OuterClass.HeatOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeatOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeatOutput)
        ds.project.service1.Service1OuterClass.HeatOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service1.Service1OuterClass.HeatOutput.class, ds.project.service1.Service1OuterClass.HeatOutput.Builder.class);
      }

      // Construct using ds.project.service1.Service1OuterClass.HeatOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        kW_ = 0D;

        bTU_ = 0D;

        error_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service1.Service1OuterClass.internal_static_HeatOutput_descriptor;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutput getDefaultInstanceForType() {
        return ds.project.service1.Service1OuterClass.HeatOutput.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutput build() {
        ds.project.service1.Service1OuterClass.HeatOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.HeatOutput buildPartial() {
        ds.project.service1.Service1OuterClass.HeatOutput result = new ds.project.service1.Service1OuterClass.HeatOutput(this);
        result.kW_ = kW_;
        result.bTU_ = bTU_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service1.Service1OuterClass.HeatOutput) {
          return mergeFrom((ds.project.service1.Service1OuterClass.HeatOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service1.Service1OuterClass.HeatOutput other) {
        if (other == ds.project.service1.Service1OuterClass.HeatOutput.getDefaultInstance()) return this;
        if (other.getKW() != 0D) {
          setKW(other.getKW());
        }
        if (other.getBTU() != 0D) {
          setBTU(other.getBTU());
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service1.Service1OuterClass.HeatOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service1.Service1OuterClass.HeatOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double kW_ ;
      /**
       * <code>double kW = 1;</code>
       */
      public double getKW() {
        return kW_;
      }
      /**
       * <code>double kW = 1;</code>
       */
      public Builder setKW(double value) {
        
        kW_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double kW = 1;</code>
       */
      public Builder clearKW() {
        
        kW_ = 0D;
        onChanged();
        return this;
      }

      private double bTU_ ;
      /**
       * <code>double BTU = 2;</code>
       */
      public double getBTU() {
        return bTU_;
      }
      /**
       * <code>double BTU = 2;</code>
       */
      public Builder setBTU(double value) {
        
        bTU_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double BTU = 2;</code>
       */
      public Builder clearBTU() {
        
        bTU_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeatOutput)
    }

    // @@protoc_insertion_point(class_scope:HeatOutput)
    private static final ds.project.service1.Service1OuterClass.HeatOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service1.Service1OuterClass.HeatOutput();
    }

    public static ds.project.service1.Service1OuterClass.HeatOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeatOutput>
        PARSER = new com.google.protobuf.AbstractParser<HeatOutput>() {
      @java.lang.Override
      public HeatOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeatOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeatOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeatOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service1.Service1OuterClass.HeatOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CostElectricRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CostElectricRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double consumptionkW = 1;</code>
     */
    double getConsumptionkW();

    /**
     * <code>double kWCost = 2;</code>
     */
    double getKWCost();
  }
  /**
   * Protobuf type {@code CostElectricRequest}
   */
  public  static final class CostElectricRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CostElectricRequest)
      CostElectricRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CostElectricRequest.newBuilder() to construct.
    private CostElectricRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CostElectricRequest() {
      consumptionkW_ = 0D;
      kWCost_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CostElectricRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              consumptionkW_ = input.readDouble();
              break;
            }
            case 17: {

              kWCost_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service1.Service1OuterClass.internal_static_CostElectricRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service1.Service1OuterClass.internal_static_CostElectricRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service1.Service1OuterClass.CostElectricRequest.class, ds.project.service1.Service1OuterClass.CostElectricRequest.Builder.class);
    }

    public static final int CONSUMPTIONKW_FIELD_NUMBER = 1;
    private double consumptionkW_;
    /**
     * <code>double consumptionkW = 1;</code>
     */
    public double getConsumptionkW() {
      return consumptionkW_;
    }

    public static final int KWCOST_FIELD_NUMBER = 2;
    private double kWCost_;
    /**
     * <code>double kWCost = 2;</code>
     */
    public double getKWCost() {
      return kWCost_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (consumptionkW_ != 0D) {
        output.writeDouble(1, consumptionkW_);
      }
      if (kWCost_ != 0D) {
        output.writeDouble(2, kWCost_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (consumptionkW_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, consumptionkW_);
      }
      if (kWCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, kWCost_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service1.Service1OuterClass.CostElectricRequest)) {
        return super.equals(obj);
      }
      ds.project.service1.Service1OuterClass.CostElectricRequest other = (ds.project.service1.Service1OuterClass.CostElectricRequest) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getConsumptionkW())
          == java.lang.Double.doubleToLongBits(
              other.getConsumptionkW()));
      result = result && (
          java.lang.Double.doubleToLongBits(getKWCost())
          == java.lang.Double.doubleToLongBits(
              other.getKWCost()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONSUMPTIONKW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getConsumptionkW()));
      hash = (37 * hash) + KWCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKWCost()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service1.Service1OuterClass.CostElectricRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CostElectricRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CostElectricRequest)
        ds.project.service1.Service1OuterClass.CostElectricRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service1.Service1OuterClass.CostElectricRequest.class, ds.project.service1.Service1OuterClass.CostElectricRequest.Builder.class);
      }

      // Construct using ds.project.service1.Service1OuterClass.CostElectricRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        consumptionkW_ = 0D;

        kWCost_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricRequest_descriptor;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricRequest getDefaultInstanceForType() {
        return ds.project.service1.Service1OuterClass.CostElectricRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricRequest build() {
        ds.project.service1.Service1OuterClass.CostElectricRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricRequest buildPartial() {
        ds.project.service1.Service1OuterClass.CostElectricRequest result = new ds.project.service1.Service1OuterClass.CostElectricRequest(this);
        result.consumptionkW_ = consumptionkW_;
        result.kWCost_ = kWCost_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service1.Service1OuterClass.CostElectricRequest) {
          return mergeFrom((ds.project.service1.Service1OuterClass.CostElectricRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service1.Service1OuterClass.CostElectricRequest other) {
        if (other == ds.project.service1.Service1OuterClass.CostElectricRequest.getDefaultInstance()) return this;
        if (other.getConsumptionkW() != 0D) {
          setConsumptionkW(other.getConsumptionkW());
        }
        if (other.getKWCost() != 0D) {
          setKWCost(other.getKWCost());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service1.Service1OuterClass.CostElectricRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service1.Service1OuterClass.CostElectricRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double consumptionkW_ ;
      /**
       * <code>double consumptionkW = 1;</code>
       */
      public double getConsumptionkW() {
        return consumptionkW_;
      }
      /**
       * <code>double consumptionkW = 1;</code>
       */
      public Builder setConsumptionkW(double value) {
        
        consumptionkW_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double consumptionkW = 1;</code>
       */
      public Builder clearConsumptionkW() {
        
        consumptionkW_ = 0D;
        onChanged();
        return this;
      }

      private double kWCost_ ;
      /**
       * <code>double kWCost = 2;</code>
       */
      public double getKWCost() {
        return kWCost_;
      }
      /**
       * <code>double kWCost = 2;</code>
       */
      public Builder setKWCost(double value) {
        
        kWCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double kWCost = 2;</code>
       */
      public Builder clearKWCost() {
        
        kWCost_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CostElectricRequest)
    }

    // @@protoc_insertion_point(class_scope:CostElectricRequest)
    private static final ds.project.service1.Service1OuterClass.CostElectricRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service1.Service1OuterClass.CostElectricRequest();
    }

    public static ds.project.service1.Service1OuterClass.CostElectricRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CostElectricRequest>
        PARSER = new com.google.protobuf.AbstractParser<CostElectricRequest>() {
      @java.lang.Override
      public CostElectricRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CostElectricRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CostElectricRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CostElectricRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service1.Service1OuterClass.CostElectricRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CostElectricityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CostElectricity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double weekCost = 1;</code>
     */
    double getWeekCost();

    /**
     * <code>double monthCost = 2;</code>
     */
    double getMonthCost();

    /**
     * <code>double annualCost = 3;</code>
     */
    double getAnnualCost();

    /**
     * <code>string error = 4;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code CostElectricity}
   */
  public  static final class CostElectricity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CostElectricity)
      CostElectricityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CostElectricity.newBuilder() to construct.
    private CostElectricity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CostElectricity() {
      weekCost_ = 0D;
      monthCost_ = 0D;
      annualCost_ = 0D;
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CostElectricity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              weekCost_ = input.readDouble();
              break;
            }
            case 17: {

              monthCost_ = input.readDouble();
              break;
            }
            case 25: {

              annualCost_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service1.Service1OuterClass.internal_static_CostElectricity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service1.Service1OuterClass.internal_static_CostElectricity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service1.Service1OuterClass.CostElectricity.class, ds.project.service1.Service1OuterClass.CostElectricity.Builder.class);
    }

    public static final int WEEKCOST_FIELD_NUMBER = 1;
    private double weekCost_;
    /**
     * <code>double weekCost = 1;</code>
     */
    public double getWeekCost() {
      return weekCost_;
    }

    public static final int MONTHCOST_FIELD_NUMBER = 2;
    private double monthCost_;
    /**
     * <code>double monthCost = 2;</code>
     */
    public double getMonthCost() {
      return monthCost_;
    }

    public static final int ANNUALCOST_FIELD_NUMBER = 3;
    private double annualCost_;
    /**
     * <code>double annualCost = 3;</code>
     */
    public double getAnnualCost() {
      return annualCost_;
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 4;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (weekCost_ != 0D) {
        output.writeDouble(1, weekCost_);
      }
      if (monthCost_ != 0D) {
        output.writeDouble(2, monthCost_);
      }
      if (annualCost_ != 0D) {
        output.writeDouble(3, annualCost_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, error_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (weekCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, weekCost_);
      }
      if (monthCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, monthCost_);
      }
      if (annualCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, annualCost_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service1.Service1OuterClass.CostElectricity)) {
        return super.equals(obj);
      }
      ds.project.service1.Service1OuterClass.CostElectricity other = (ds.project.service1.Service1OuterClass.CostElectricity) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getWeekCost())
          == java.lang.Double.doubleToLongBits(
              other.getWeekCost()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMonthCost())
          == java.lang.Double.doubleToLongBits(
              other.getMonthCost()));
      result = result && (
          java.lang.Double.doubleToLongBits(getAnnualCost())
          == java.lang.Double.doubleToLongBits(
              other.getAnnualCost()));
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WEEKCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeekCost()));
      hash = (37 * hash) + MONTHCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMonthCost()));
      hash = (37 * hash) + ANNUALCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAnnualCost()));
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service1.Service1OuterClass.CostElectricity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service1.Service1OuterClass.CostElectricity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CostElectricity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CostElectricity)
        ds.project.service1.Service1OuterClass.CostElectricityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service1.Service1OuterClass.CostElectricity.class, ds.project.service1.Service1OuterClass.CostElectricity.Builder.class);
      }

      // Construct using ds.project.service1.Service1OuterClass.CostElectricity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        weekCost_ = 0D;

        monthCost_ = 0D;

        annualCost_ = 0D;

        error_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service1.Service1OuterClass.internal_static_CostElectricity_descriptor;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricity getDefaultInstanceForType() {
        return ds.project.service1.Service1OuterClass.CostElectricity.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricity build() {
        ds.project.service1.Service1OuterClass.CostElectricity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service1.Service1OuterClass.CostElectricity buildPartial() {
        ds.project.service1.Service1OuterClass.CostElectricity result = new ds.project.service1.Service1OuterClass.CostElectricity(this);
        result.weekCost_ = weekCost_;
        result.monthCost_ = monthCost_;
        result.annualCost_ = annualCost_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service1.Service1OuterClass.CostElectricity) {
          return mergeFrom((ds.project.service1.Service1OuterClass.CostElectricity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service1.Service1OuterClass.CostElectricity other) {
        if (other == ds.project.service1.Service1OuterClass.CostElectricity.getDefaultInstance()) return this;
        if (other.getWeekCost() != 0D) {
          setWeekCost(other.getWeekCost());
        }
        if (other.getMonthCost() != 0D) {
          setMonthCost(other.getMonthCost());
        }
        if (other.getAnnualCost() != 0D) {
          setAnnualCost(other.getAnnualCost());
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service1.Service1OuterClass.CostElectricity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service1.Service1OuterClass.CostElectricity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double weekCost_ ;
      /**
       * <code>double weekCost = 1;</code>
       */
      public double getWeekCost() {
        return weekCost_;
      }
      /**
       * <code>double weekCost = 1;</code>
       */
      public Builder setWeekCost(double value) {
        
        weekCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weekCost = 1;</code>
       */
      public Builder clearWeekCost() {
        
        weekCost_ = 0D;
        onChanged();
        return this;
      }

      private double monthCost_ ;
      /**
       * <code>double monthCost = 2;</code>
       */
      public double getMonthCost() {
        return monthCost_;
      }
      /**
       * <code>double monthCost = 2;</code>
       */
      public Builder setMonthCost(double value) {
        
        monthCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double monthCost = 2;</code>
       */
      public Builder clearMonthCost() {
        
        monthCost_ = 0D;
        onChanged();
        return this;
      }

      private double annualCost_ ;
      /**
       * <code>double annualCost = 3;</code>
       */
      public double getAnnualCost() {
        return annualCost_;
      }
      /**
       * <code>double annualCost = 3;</code>
       */
      public Builder setAnnualCost(double value) {
        
        annualCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double annualCost = 3;</code>
       */
      public Builder clearAnnualCost() {
        
        annualCost_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 4;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CostElectricity)
    }

    // @@protoc_insertion_point(class_scope:CostElectricity)
    private static final ds.project.service1.Service1OuterClass.CostElectricity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service1.Service1OuterClass.CostElectricity();
    }

    public static ds.project.service1.Service1OuterClass.CostElectricity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CostElectricity>
        PARSER = new com.google.protobuf.AbstractParser<CostElectricity>() {
      @java.lang.Override
      public CostElectricity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CostElectricity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CostElectricity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CostElectricity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service1.Service1OuterClass.CostElectricity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatOutputRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatOutputRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatOutput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CostElectricRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CostElectricRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CostElectricity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CostElectricity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\"Q\n\021HeatOutputRequest\022\022\n" +
      "\nwidth_room\030\001 \001(\001\022\023\n\013length_room\030\002 \001(\001\022\023" +
      "\n\013height_room\030\003 \001(\001\"4\n\nHeatOutput\022\n\n\002kW\030" +
      "\001 \001(\001\022\013\n\003BTU\030\002 \001(\001\022\r\n\005error\030\003 \001(\t\"<\n\023Cos" +
      "tElectricRequest\022\025\n\rconsumptionkW\030\001 \001(\001\022" +
      "\016\n\006kWCost\030\002 \001(\001\"Y\n\017CostElectricity\022\020\n\010we" +
      "ekCost\030\001 \001(\001\022\021\n\tmonthCost\030\002 \001(\001\022\022\n\nannua" +
      "lCost\030\003 \001(\001\022\r\n\005error\030\004 \001(\t2v\n\010Service1\0220" +
      "\n\rgetHeatOutput\022\022.HeatOutputRequest\032\013.He" +
      "atOutput\0228\n\016getCostOfElect\022\024.CostElectri" +
      "cRequest\032\020.CostElectricityB\025\n\023ds.project" +
      ".service1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeatOutputRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeatOutputRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatOutputRequest_descriptor,
        new java.lang.String[] { "WidthRoom", "LengthRoom", "HeightRoom", });
    internal_static_HeatOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeatOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatOutput_descriptor,
        new java.lang.String[] { "KW", "BTU", "Error", });
    internal_static_CostElectricRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CostElectricRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CostElectricRequest_descriptor,
        new java.lang.String[] { "ConsumptionkW", "KWCost", });
    internal_static_CostElectricity_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CostElectricity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CostElectricity_descriptor,
        new java.lang.String[] { "WeekCost", "MonthCost", "AnnualCost", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
