// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package ds.project.service4;

public final class Service4OuterClass {
  private Service4OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface consumptionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:consumptionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.consumptionRequest.Year year = 1;</code>
     */
    int getYearValue();
    /**
     * <code>.consumptionRequest.Year year = 1;</code>
     */
    ds.project.service4.Service4OuterClass.consumptionRequest.Year getYear();

    /**
     * <code>.consumptionRequest.Month month = 2;</code>
     */
    int getMonthValue();
    /**
     * <code>.consumptionRequest.Month month = 2;</code>
     */
    ds.project.service4.Service4OuterClass.consumptionRequest.Month getMonth();
  }
  /**
   * Protobuf type {@code consumptionRequest}
   */
  public  static final class consumptionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:consumptionRequest)
      consumptionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use consumptionRequest.newBuilder() to construct.
    private consumptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private consumptionRequest() {
      year_ = 0;
      month_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private consumptionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              year_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              month_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service4.Service4OuterClass.internal_static_consumptionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service4.Service4OuterClass.internal_static_consumptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service4.Service4OuterClass.consumptionRequest.class, ds.project.service4.Service4OuterClass.consumptionRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code consumptionRequest.Year}
     */
    public enum Year
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Y_2022 = 0;</code>
       */
      Y_2022(0),
      /**
       * <code>Y_2023 = 1;</code>
       */
      Y_2023(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Y_2022 = 0;</code>
       */
      public static final int Y_2022_VALUE = 0;
      /**
       * <code>Y_2023 = 1;</code>
       */
      public static final int Y_2023_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Year valueOf(int value) {
        return forNumber(value);
      }

      public static Year forNumber(int value) {
        switch (value) {
          case 0: return Y_2022;
          case 1: return Y_2023;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Year>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Year> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Year>() {
              public Year findValueByNumber(int number) {
                return Year.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ds.project.service4.Service4OuterClass.consumptionRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Year[] VALUES = values();

      public static Year valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Year(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:consumptionRequest.Year)
    }

    /**
     * Protobuf enum {@code consumptionRequest.Month}
     */
    public enum Month
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JAN = 0;</code>
       */
      JAN(0),
      /**
       * <code>FEB = 1;</code>
       */
      FEB(1),
      /**
       * <code>MAR = 2;</code>
       */
      MAR(2),
      /**
       * <code>APR = 3;</code>
       */
      APR(3),
      /**
       * <code>MAY = 4;</code>
       */
      MAY(4),
      /**
       * <code>JUN = 5;</code>
       */
      JUN(5),
      /**
       * <code>JUL = 6;</code>
       */
      JUL(6),
      /**
       * <code>AUG = 7;</code>
       */
      AUG(7),
      /**
       * <code>SEP = 8;</code>
       */
      SEP(8),
      /**
       * <code>OCT = 9;</code>
       */
      OCT(9),
      /**
       * <code>NOV = 10;</code>
       */
      NOV(10),
      /**
       * <code>DEC = 11;</code>
       */
      DEC(11),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>JAN = 0;</code>
       */
      public static final int JAN_VALUE = 0;
      /**
       * <code>FEB = 1;</code>
       */
      public static final int FEB_VALUE = 1;
      /**
       * <code>MAR = 2;</code>
       */
      public static final int MAR_VALUE = 2;
      /**
       * <code>APR = 3;</code>
       */
      public static final int APR_VALUE = 3;
      /**
       * <code>MAY = 4;</code>
       */
      public static final int MAY_VALUE = 4;
      /**
       * <code>JUN = 5;</code>
       */
      public static final int JUN_VALUE = 5;
      /**
       * <code>JUL = 6;</code>
       */
      public static final int JUL_VALUE = 6;
      /**
       * <code>AUG = 7;</code>
       */
      public static final int AUG_VALUE = 7;
      /**
       * <code>SEP = 8;</code>
       */
      public static final int SEP_VALUE = 8;
      /**
       * <code>OCT = 9;</code>
       */
      public static final int OCT_VALUE = 9;
      /**
       * <code>NOV = 10;</code>
       */
      public static final int NOV_VALUE = 10;
      /**
       * <code>DEC = 11;</code>
       */
      public static final int DEC_VALUE = 11;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Month valueOf(int value) {
        return forNumber(value);
      }

      public static Month forNumber(int value) {
        switch (value) {
          case 0: return JAN;
          case 1: return FEB;
          case 2: return MAR;
          case 3: return APR;
          case 4: return MAY;
          case 5: return JUN;
          case 6: return JUL;
          case 7: return AUG;
          case 8: return SEP;
          case 9: return OCT;
          case 10: return NOV;
          case 11: return DEC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Month>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Month> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Month>() {
              public Month findValueByNumber(int number) {
                return Month.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ds.project.service4.Service4OuterClass.consumptionRequest.getDescriptor().getEnumTypes().get(1);
      }

      private static final Month[] VALUES = values();

      public static Month valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Month(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:consumptionRequest.Month)
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    /**
     * <code>.consumptionRequest.Year year = 1;</code>
     */
    public int getYearValue() {
      return year_;
    }
    /**
     * <code>.consumptionRequest.Year year = 1;</code>
     */
    public ds.project.service4.Service4OuterClass.consumptionRequest.Year getYear() {
      @SuppressWarnings("deprecation")
      ds.project.service4.Service4OuterClass.consumptionRequest.Year result = ds.project.service4.Service4OuterClass.consumptionRequest.Year.valueOf(year_);
      return result == null ? ds.project.service4.Service4OuterClass.consumptionRequest.Year.UNRECOGNIZED : result;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>.consumptionRequest.Month month = 2;</code>
     */
    public int getMonthValue() {
      return month_;
    }
    /**
     * <code>.consumptionRequest.Month month = 2;</code>
     */
    public ds.project.service4.Service4OuterClass.consumptionRequest.Month getMonth() {
      @SuppressWarnings("deprecation")
      ds.project.service4.Service4OuterClass.consumptionRequest.Month result = ds.project.service4.Service4OuterClass.consumptionRequest.Month.valueOf(month_);
      return result == null ? ds.project.service4.Service4OuterClass.consumptionRequest.Month.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (year_ != ds.project.service4.Service4OuterClass.consumptionRequest.Year.Y_2022.getNumber()) {
        output.writeEnum(1, year_);
      }
      if (month_ != ds.project.service4.Service4OuterClass.consumptionRequest.Month.JAN.getNumber()) {
        output.writeEnum(2, month_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (year_ != ds.project.service4.Service4OuterClass.consumptionRequest.Year.Y_2022.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, year_);
      }
      if (month_ != ds.project.service4.Service4OuterClass.consumptionRequest.Month.JAN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, month_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service4.Service4OuterClass.consumptionRequest)) {
        return super.equals(obj);
      }
      ds.project.service4.Service4OuterClass.consumptionRequest other = (ds.project.service4.Service4OuterClass.consumptionRequest) obj;

      boolean result = true;
      result = result && year_ == other.year_;
      result = result && month_ == other.month_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + year_;
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + month_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.consumptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service4.Service4OuterClass.consumptionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code consumptionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:consumptionRequest)
        ds.project.service4.Service4OuterClass.consumptionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service4.Service4OuterClass.internal_static_consumptionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service4.Service4OuterClass.internal_static_consumptionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service4.Service4OuterClass.consumptionRequest.class, ds.project.service4.Service4OuterClass.consumptionRequest.Builder.class);
      }

      // Construct using ds.project.service4.Service4OuterClass.consumptionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = 0;

        month_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service4.Service4OuterClass.internal_static_consumptionRequest_descriptor;
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.consumptionRequest getDefaultInstanceForType() {
        return ds.project.service4.Service4OuterClass.consumptionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.consumptionRequest build() {
        ds.project.service4.Service4OuterClass.consumptionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.consumptionRequest buildPartial() {
        ds.project.service4.Service4OuterClass.consumptionRequest result = new ds.project.service4.Service4OuterClass.consumptionRequest(this);
        result.year_ = year_;
        result.month_ = month_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service4.Service4OuterClass.consumptionRequest) {
          return mergeFrom((ds.project.service4.Service4OuterClass.consumptionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service4.Service4OuterClass.consumptionRequest other) {
        if (other == ds.project.service4.Service4OuterClass.consumptionRequest.getDefaultInstance()) return this;
        if (other.year_ != 0) {
          setYearValue(other.getYearValue());
        }
        if (other.month_ != 0) {
          setMonthValue(other.getMonthValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service4.Service4OuterClass.consumptionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service4.Service4OuterClass.consumptionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int year_ = 0;
      /**
       * <code>.consumptionRequest.Year year = 1;</code>
       */
      public int getYearValue() {
        return year_;
      }
      /**
       * <code>.consumptionRequest.Year year = 1;</code>
       */
      public Builder setYearValue(int value) {
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.consumptionRequest.Year year = 1;</code>
       */
      public ds.project.service4.Service4OuterClass.consumptionRequest.Year getYear() {
        @SuppressWarnings("deprecation")
        ds.project.service4.Service4OuterClass.consumptionRequest.Year result = ds.project.service4.Service4OuterClass.consumptionRequest.Year.valueOf(year_);
        return result == null ? ds.project.service4.Service4OuterClass.consumptionRequest.Year.UNRECOGNIZED : result;
      }
      /**
       * <code>.consumptionRequest.Year year = 1;</code>
       */
      public Builder setYear(ds.project.service4.Service4OuterClass.consumptionRequest.Year value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        year_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.consumptionRequest.Year year = 1;</code>
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ = 0;
      /**
       * <code>.consumptionRequest.Month month = 2;</code>
       */
      public int getMonthValue() {
        return month_;
      }
      /**
       * <code>.consumptionRequest.Month month = 2;</code>
       */
      public Builder setMonthValue(int value) {
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.consumptionRequest.Month month = 2;</code>
       */
      public ds.project.service4.Service4OuterClass.consumptionRequest.Month getMonth() {
        @SuppressWarnings("deprecation")
        ds.project.service4.Service4OuterClass.consumptionRequest.Month result = ds.project.service4.Service4OuterClass.consumptionRequest.Month.valueOf(month_);
        return result == null ? ds.project.service4.Service4OuterClass.consumptionRequest.Month.UNRECOGNIZED : result;
      }
      /**
       * <code>.consumptionRequest.Month month = 2;</code>
       */
      public Builder setMonth(ds.project.service4.Service4OuterClass.consumptionRequest.Month value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        month_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.consumptionRequest.Month month = 2;</code>
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:consumptionRequest)
    }

    // @@protoc_insertion_point(class_scope:consumptionRequest)
    private static final ds.project.service4.Service4OuterClass.consumptionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service4.Service4OuterClass.consumptionRequest();
    }

    public static ds.project.service4.Service4OuterClass.consumptionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<consumptionRequest>
        PARSER = new com.google.protobuf.AbstractParser<consumptionRequest>() {
      @java.lang.Override
      public consumptionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new consumptionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<consumptionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<consumptionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service4.Service4OuterClass.consumptionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConsumptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Consumption)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string consumption = 1;</code>
     */
    java.lang.String getConsumption();
    /**
     * <code>string consumption = 1;</code>
     */
    com.google.protobuf.ByteString
        getConsumptionBytes();

    /**
     * <code>string total = 2;</code>
     */
    java.lang.String getTotal();
    /**
     * <code>string total = 2;</code>
     */
    com.google.protobuf.ByteString
        getTotalBytes();

    /**
     * <code>string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code Consumption}
   */
  public  static final class Consumption extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Consumption)
      ConsumptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Consumption.newBuilder() to construct.
    private Consumption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Consumption() {
      consumption_ = "";
      total_ = "";
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Consumption(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              consumption_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              total_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.project.service4.Service4OuterClass.internal_static_Consumption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.project.service4.Service4OuterClass.internal_static_Consumption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.project.service4.Service4OuterClass.Consumption.class, ds.project.service4.Service4OuterClass.Consumption.Builder.class);
    }

    public static final int CONSUMPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object consumption_;
    /**
     * <code>string consumption = 1;</code>
     */
    public java.lang.String getConsumption() {
      java.lang.Object ref = consumption_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumption_ = s;
        return s;
      }
    }
    /**
     * <code>string consumption = 1;</code>
     */
    public com.google.protobuf.ByteString
        getConsumptionBytes() {
      java.lang.Object ref = consumption_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_FIELD_NUMBER = 2;
    private volatile java.lang.Object total_;
    /**
     * <code>string total = 2;</code>
     */
    public java.lang.String getTotal() {
      java.lang.Object ref = total_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        total_ = s;
        return s;
      }
    }
    /**
     * <code>string total = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTotalBytes() {
      java.lang.Object ref = total_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        total_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getConsumptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumption_);
      }
      if (!getTotalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, total_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, error_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getConsumptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumption_);
      }
      if (!getTotalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, total_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.project.service4.Service4OuterClass.Consumption)) {
        return super.equals(obj);
      }
      ds.project.service4.Service4OuterClass.Consumption other = (ds.project.service4.Service4OuterClass.Consumption) obj;

      boolean result = true;
      result = result && getConsumption()
          .equals(other.getConsumption());
      result = result && getTotal()
          .equals(other.getTotal());
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONSUMPTION_FIELD_NUMBER;
      hash = (53 * hash) + getConsumption().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.project.service4.Service4OuterClass.Consumption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.project.service4.Service4OuterClass.Consumption prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Consumption}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Consumption)
        ds.project.service4.Service4OuterClass.ConsumptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.project.service4.Service4OuterClass.internal_static_Consumption_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.project.service4.Service4OuterClass.internal_static_Consumption_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.project.service4.Service4OuterClass.Consumption.class, ds.project.service4.Service4OuterClass.Consumption.Builder.class);
      }

      // Construct using ds.project.service4.Service4OuterClass.Consumption.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        consumption_ = "";

        total_ = "";

        error_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.project.service4.Service4OuterClass.internal_static_Consumption_descriptor;
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.Consumption getDefaultInstanceForType() {
        return ds.project.service4.Service4OuterClass.Consumption.getDefaultInstance();
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.Consumption build() {
        ds.project.service4.Service4OuterClass.Consumption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.project.service4.Service4OuterClass.Consumption buildPartial() {
        ds.project.service4.Service4OuterClass.Consumption result = new ds.project.service4.Service4OuterClass.Consumption(this);
        result.consumption_ = consumption_;
        result.total_ = total_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.project.service4.Service4OuterClass.Consumption) {
          return mergeFrom((ds.project.service4.Service4OuterClass.Consumption)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.project.service4.Service4OuterClass.Consumption other) {
        if (other == ds.project.service4.Service4OuterClass.Consumption.getDefaultInstance()) return this;
        if (!other.getConsumption().isEmpty()) {
          consumption_ = other.consumption_;
          onChanged();
        }
        if (!other.getTotal().isEmpty()) {
          total_ = other.total_;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.project.service4.Service4OuterClass.Consumption parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.project.service4.Service4OuterClass.Consumption) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object consumption_ = "";
      /**
       * <code>string consumption = 1;</code>
       */
      public java.lang.String getConsumption() {
        java.lang.Object ref = consumption_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consumption_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string consumption = 1;</code>
       */
      public com.google.protobuf.ByteString
          getConsumptionBytes() {
        java.lang.Object ref = consumption_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumption_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string consumption = 1;</code>
       */
      public Builder setConsumption(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consumption_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string consumption = 1;</code>
       */
      public Builder clearConsumption() {
        
        consumption_ = getDefaultInstance().getConsumption();
        onChanged();
        return this;
      }
      /**
       * <code>string consumption = 1;</code>
       */
      public Builder setConsumptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        consumption_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object total_ = "";
      /**
       * <code>string total = 2;</code>
       */
      public java.lang.String getTotal() {
        java.lang.Object ref = total_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          total_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string total = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTotalBytes() {
        java.lang.Object ref = total_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          total_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string total = 2;</code>
       */
      public Builder setTotal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string total = 2;</code>
       */
      public Builder clearTotal() {
        
        total_ = getDefaultInstance().getTotal();
        onChanged();
        return this;
      }
      /**
       * <code>string total = 2;</code>
       */
      public Builder setTotalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        total_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Consumption)
    }

    // @@protoc_insertion_point(class_scope:Consumption)
    private static final ds.project.service4.Service4OuterClass.Consumption DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.project.service4.Service4OuterClass.Consumption();
    }

    public static ds.project.service4.Service4OuterClass.Consumption getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Consumption>
        PARSER = new com.google.protobuf.AbstractParser<Consumption>() {
      @java.lang.Override
      public Consumption parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Consumption(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Consumption> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Consumption> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.project.service4.Service4OuterClass.Consumption getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consumptionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_consumptionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Consumption_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Consumption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service4.proto\"\373\001\n\022consumptionRequest\022" +
      "&\n\004year\030\001 \001(\0162\030.consumptionRequest.Year\022" +
      "(\n\005month\030\002 \001(\0162\031.consumptionRequest.Mont" +
      "h\"\036\n\004Year\022\n\n\006Y_2022\020\000\022\n\n\006Y_2023\020\001\"s\n\005Mon" +
      "th\022\007\n\003JAN\020\000\022\007\n\003FEB\020\001\022\007\n\003MAR\020\002\022\007\n\003APR\020\003\022\007" +
      "\n\003MAY\020\004\022\007\n\003JUN\020\005\022\007\n\003JUL\020\006\022\007\n\003AUG\020\007\022\007\n\003SE" +
      "P\020\010\022\007\n\003OCT\020\t\022\007\n\003NOV\020\n\022\007\n\003DEC\020\013\"@\n\013Consum" +
      "ption\022\023\n\013consumption\030\001 \001(\t\022\r\n\005total\030\002 \001(" +
      "\t\022\r\n\005error\030\003 \001(\t2C\n\010Service4\0227\n\016getConsu" +
      "mption\022\023.consumptionRequest\032\014.Consumptio" +
      "n(\0010\001B\025\n\023ds.project.service4b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_consumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_consumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_consumptionRequest_descriptor,
        new java.lang.String[] { "Year", "Month", });
    internal_static_Consumption_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Consumption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Consumption_descriptor,
        new java.lang.String[] { "Consumption", "Total", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
